import { generateTailwindConfig } from "./tailwind-config.js";
import { generateTemplate } from "./templates.js";
import { getComponent, COMPONENT_TYPES, type ComponentType } from "./components.js";

export interface ExportFile {
  path: string;
  content: string;
}

export interface ExportProjectResult {
  projectName: string;
  style: string;
  palette: string;
  archetype: string;
  files: ExportFile[];
  setupInstructions: string;
}

export function exportProject(
  style: string,
  palette: string,
  archetype: string,
  projectName = "my-project"
): ExportProjectResult {
  const { code: tailwindConfig } = generateTailwindConfig(style, palette);
  const templateHtml = generateTemplate(style, palette, archetype);

  const componentFiles: ExportFile[] = COMPONENT_TYPES.map((type) => ({
    path: `components/${type}.html`,
    content: getComponent(type, style),
  }));

  const indexHtml = templateHtml.replace(
    '<script src="https://cdn.tailwindcss.com"></script>',
    `<link rel="stylesheet" href="dist/output.css">`
  ).replace(
    /<script>\n[\s\S]*?<\/script>/,
    ""
  );

  const packageJson = JSON.stringify({
    name: projectName,
    version: "1.0.0",
    scripts: {
      dev: "npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch",
      build: "npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify",
    },
    devDependencies: {
      tailwindcss: "^3.4.0",
    },
  }, null, 2);

  const inputCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`;

  const readme = `# ${projectName}

Generated by the-designer MCP — style: \`${style}\`, palette: \`${palette}\`, archetype: \`${archetype}\`.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

Open \`index.html\` in your browser.

## Files

- \`tailwind.config.js\` — Tailwind configuration with your design tokens
- \`src/input.css\` — Tailwind directives
- \`index.html\` — Main page template
- \`components/\` — Reusable component snippets
`;

  return {
    projectName,
    style,
    palette,
    archetype,
    files: [
      { path: "tailwind.config.js", content: tailwindConfig },
      { path: "src/input.css", content: inputCss },
      { path: "index.html", content: indexHtml },
      { path: "package.json", content: packageJson },
      { path: "README.md", content: readme },
      ...componentFiles,
    ],
    setupInstructions: `Run: npm install && npm run dev`,
  };
}
